### ISSUE TITLE
Is the crashes fixed yet?

### ISSUE THREAD

**Issue by bseditor** [imayushsaini/Bombsquad-Ballistica-Modded-Server#21]
What've you done to stop the recent server crashes done by people intentionally?

**Comment by Freaku17** [comment]
First up, the server runs on BombSquad v1.6.6+ and the security have increased a lot in these versions, stuffs like coming in mass numbers by same accounts caused crashes in 1.4 (maybe because of trying to authenticate clients) but they are now not affectable in latest version.

Second, scripts have all types of protection ranging from idiot people to bots. We have Spam protection, Abuse filter, rejoin spam (too many joins to server in short amounts of time), warning system, etc. Every joinee's account creation date are also checked (and in most cases bots are new accounts) and if they are too new, they are kicked immediately (the time of this can be modified in dist/ba_root/mods/setting.json)

Talking about crashes, scripts are currently stable. As next versions are released there could be slight bugs (even after we test, some things remains) so please do let us know if you are facing any errors :)

**Comment by bseditor** [comment]
> First up, the server runs on BombSquad v1.6.6+ and the security have increased a lot in these versions, stuffs like coming in mass numbers by same accounts caused crashes in 1.4 (maybe because of trying to authenticate clients) but they are now not affectable in latest version.
> 
> Second, scripts have all types of protection ranging from idiot people to bots. We have Spam protection, Abuse filter, rejoin spam (too many joins to server in short amounts of time), warning system, etc. Every joinee's account creation date are also checked (and in most cases bots are new accounts) and if they are too new, they are kicked immediately (the time of this can be modified in dist/ba_root/mods/setting.json)
> 
> Talking about crashes, scripts are currently stable. As next versions are released there could be slight bugs (even after we test, some things remains) so please do let us know if you are facing any errors :)

Thanks I make sure I report those bugs (if any) here or to smoothy directly :))
